export enum TransactionState {
  CREATED = 'CREATED',
  OFFER_MADE = 'OFFER_MADE',
  OFFER_ACCEPTED = 'OFFER_ACCEPTED',
  DOCUMENTS_PENDING = 'DOCUMENTS_PENDING',
  COMPLIANCE_CHECK = 'COMPLIANCE_CHECK',
  TRANSFER_INITIATED = 'TRANSFER_INITIATED',
  TRANSFER_COMPLETED = 'TRANSFER_COMPLETED',
}
